### ISSUE TITLE
Connection stabillity issues

### ISSUE THREAD

**Issue by R3verseCha0s** [NYAN-x-CAT/Lime-RAT#33] opened 2018-09-15 15:54 UTC
So I found that the client disconnects after some time and doesn't connect back. As you can see here, the process is running, the Pastebin IP and port are valid, but nothing in the GUI. I have waited about 15 mins and still nothing

![image](https://user-images.githubusercontent.com/36313151/45588054-4f435800-b917-11e8-9a2d-b1c2178a80b6.png)

But after terminating the client from the task manager, and reopening the exe, it showed just fine, as you can see on this image:

![image](https://user-images.githubusercontent.com/36313151/45588043-173c1500-b917-11e8-8f2d-22ab2b970feb.png)

I don't know what might be happening, I never had this issue with 0.1.8.1. I think that its something that needs to be fixed. 
P.S This happened to me in both v0.1.8.2F and v0.1.8.3C  both on Windows 7 x64 and Windows 10 x64
Here are my specs: 

![image](https://user-images.githubusercontent.com/36313151/45588034-fffd2780-b916-11e8-8a0c-6c535a5b11f9.png)

**Comment by NYAN-x-CAT** [comment] 2018-09-15 22:53
Hello @MikeTHEPro 
For better result, you should always use the client on win7 to avoid WD and firewall.
- Does the client disconnect while LimeRAT is open?
- What were you doing before the client disconnect?
- Any details would help.

**Comment by Jh0nW1cK** [comment] 2018-09-17 11:43
It is a major failure, the problem is that the client does not have persistence, and if you close the server does not reconnect until the PC is restarted (and the options in "auto task" of persistence and mining do not work well). 
I did a test with 30 clients, when closing the Lime rat server and reopening it, only 1 client connected. 
Tested in v0.1.8.3

**Comment by NYAN-x-CAT** [comment] 2018-09-17 11:47
Hello @Jh0nW1cK 
This is weird, I didn't face any of that. Are you sure that you are using the latest stub + latest limerat?

**Comment by Jh0nW1cK** [comment] 2018-09-17 12:10
Hello @NYAN-x-CAT
Absolutely secure, the first that used was the version v.0.1.8.2 to try. But I have only used version v.0.1.8.3 to install in several PCs.

**Comment by NYAN-x-CAT** [comment] 2018-09-17 12:27
@Jh0nW1cK 
I advise you to try this version  https://www.sendspace.com/file/uvy1n5 PASS=123
Update your client using this stub + old limerat. then close it and open the new limerat.
And give me feedback especially about stability issue.

**Comment by Jh0nW1cK** [comment] 2018-09-17 14:37
@NYAN-x-CAT
I have done a stability test with 1 client using v.1.0.8.4 and the result has been good. 
When I launch this version I will do a test with several clients. 

PS: I have observed that in the XMR field the CPU info is shown, if it also shows the GPU it would be very useful for mining.

**Closed as completed** 2018-09-18 21:24 UTC

**Comment by Jh0nW1cK** [comment] 2018-09-20 15:37
I have tested v0.1.8.4 with 10 clients and the problem persists. 
I close the server and when opening it only 1 client is connected, in some cases the client never connects. 
I have checked the connections of the process with netstat, in two clients there is a connection through port 443 to an IP of one proxy (cloudflare) and another one to pastebin, both for the same process...

!(https://imgur.com/1EfROQX)

!(https://m.imgur.com/a/kmcdEU2)
